In [3]:
import pandas as pd
df = pd.read_csv("C:\\Pratheeksha SJU\\6th Semester\\Machine Learning\\processed.cleveland.csv")
df

,Age,Sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,Presence
0,63,1,1,145,233,1,2,150,0,2.3,3,0,6,0
1,67,1,4,160,286,0,2,108,1,1.5,2,3,3,2
2,67,1,4,120,229,0,2,129,1,2.6,2,2,7,1
3,37,1,3,130,250,0,0,187,0,3.5,3,0,3,0
4,41,0,2,130,204,0,2,172,0,1.4,1,0,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45,1,1,110,264,0,0,132,0,1.2,2,0,7,1
299,68,1,4,144,193,1,0,141,0,3.4,2,2,7,2
300,57,1,4,130,131,0,0,115,1,1.2,2,1,7,3
301,57,0,2,130,236,0,2,174,0,0.0,2,1,3,1
302,38,1,3,138,175,0,0,173,0,0.0,1,?,3,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Age       303 non-null    int64
 1   Sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    object
 12  thal      303 non-null    object
 13  Presence  303 non-null    int64
dtypes: float64(1), int64(11), object(2)
memory usage: 33.3+ KB

In [5]:
df.describe()

,Age,Sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,Presence
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.438944,0.679868,3.158416,131.689769,246.693069,0.148515,0.990099,149.607261,0.326733,1.039604,1.600660,0.937294
std,9.038662,0.467299,0.960126,17.599748,51.776918,0.356198,0.994971,22.875003,0.469794,1.161075,0.616226,1.228536
min,29.000000,0.000000,1.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,1.000000,0.000000
25%,48.000000,0.000000,3.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000
50%,56.000000,1.000000,3.000000,130.000000,241.000000,0.000000,1.000000,153.000000,0.000000,0.800000,2.000000,0.000000
75%,61.000000,1.000000,4.000000,140.000000,275.000000,0.000000,2.000000,166.000000,1.000000,1.600000,2.000000,2.000000
max,77.000000,1.000000,4.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,3.000000,4.000000

In [6]:
df.isnull().sum()

Age         0
Sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
Presence    0
dtype: int64

In [7]:
corr_AB = df['Age'].corr(df['Presence'])
print("Correlation: Age X Presence ")
print(corr_AB)

Correlation: Age X Presence
0.22285341927595312

In [46]:
corr_AC = df['Presence'].corr(df['cp'])
print("Correlation: Presence X cp ")
print(corr_AC)

corr_AD = df['Presence'].corr(df['trestbps'])
print("Correlation: Presence X trestbps ")
print(corr_AD)

corr_BC = df['Presence'].corr(df['cp'])
print("Correlation: Presence X cp ")
print(corr_BC)

corr_BD = df['exang'].corr(df['Presence'])
print("Correlation: exang X Presence ")
print(corr_BD)

Correlation: Presence X cp
0.40707542149829773
Correlation: Presence X trestbps
0.15775407626368673
Correlation: Presence X cp
0.40707542149829773
Correlation: exang X Presence
0.39705730162267466

In [9]:
#Converting strings to numeric
df['ca'] = pd.to_numeric(df['ca'], errors = 'coerce')
df['thal'] = pd.to_numeric(df['thal'], errors = 'coerce')

In [10]:
corr_df = df.corr(numeric_only=True)
print(corr_df)

               Age       Sex        cp  trestbps      chol       fbs  \
Age       1.000000 -0.097542  0.104139  0.284946  0.208950  0.118530
Sex      -0.097542  1.000000  0.010084 -0.064456 -0.199915  0.047862
cp        0.104139  0.010084  1.000000 -0.036077  0.072319 -0.039975
trestbps  0.284946 -0.064456 -0.036077  1.000000  0.130120  0.175340
chol      0.208950 -0.199915  0.072319  0.130120  1.000000  0.009841
fbs       0.118530  0.047862 -0.039975  0.175340  0.009841  1.000000
restecg   0.148868  0.021647  0.067505  0.146560  0.171043  0.069564
thalach  -0.393806 -0.048663 -0.334422 -0.045351 -0.003432 -0.007854
exang     0.091661  0.146201  0.384060  0.064762  0.061310  0.025665
oldpeak   0.203805  0.102173  0.202277  0.189171  0.046564  0.005747
slope     0.161770  0.037533  0.152050  0.117382 -0.004062  0.059894
ca        0.362605  0.093185  0.233214  0.098773  0.119000  0.145478
thal      0.127389  0.380936  0.265246  0.133554  0.014214  0.071358
Presence  0.222853  0.224469  0.407075  0.157754  0.070909  0.059186

           restecg   thalach     exang   oldpeak     slope        ca  \
Age       0.148868 -0.393806  0.091661  0.203805  0.161770  0.362605
Sex       0.021647 -0.048663  0.146201  0.102173  0.037533  0.093185
cp        0.067505 -0.334422  0.384060  0.202277  0.152050  0.233214
trestbps  0.146560 -0.045351  0.064762  0.189171  0.117382  0.098773
chol      0.171043 -0.003432  0.061310  0.046564 -0.004062  0.119000
fbs       0.069564 -0.007854  0.025665  0.005747  0.059894  0.145478
restecg   1.000000 -0.083389  0.084867  0.114133  0.133946  0.128343
thalach  -0.083389  1.000000 -0.378103 -0.343085 -0.385601 -0.264246
exang     0.084867 -0.378103  1.000000  0.288223  0.257748  0.145570
oldpeak   0.114133 -0.343085  0.288223  1.000000  0.577537  0.295832
slope     0.133946 -0.385601  0.257748  0.577537  1.000000  0.110119
ca        0.128343 -0.264246  0.145570  0.295832  0.110119  1.000000
thal      0.024531 -0.279631  0.329680  0.341004  0.287232  0.256382
Presence  0.183696 -0.415040  0.397057  0.504092  0.377957  0.518909

              thal  Presence
Age       0.127389  0.222853
Sex       0.380936  0.224469
cp        0.265246  0.407075
trestbps  0.133554  0.157754
chol      0.014214  0.070909
fbs       0.071358  0.059186
restecg   0.024531  0.183696
thalach  -0.279631 -0.415040
exang     0.329680  0.397057
oldpeak   0.341004  0.504092
slope     0.287232  0.377957
ca        0.256382  0.518909
thal      1.000000  0.509923
Presence  0.509923  1.000000

In [11]:
#Dropping negatively correlated columns with our O/p
df_new = df.drop("thalach", axis = 1)

#Drop all duplicate rows
df_new = df_new.drop_duplicates()

In [12]:
df_new

,Age,Sex,cp,trestbps,chol,fbs,restecg,exang,oldpeak,slope,ca,thal,Presence
0,63,1,1,145,233,1,2,0,2.3,3,0.0,6.0,0
1,67,1,4,160,286,0,2,1,1.5,2,3.0,3.0,2
2,67,1,4,120,229,0,2,1,2.6,2,2.0,7.0,1
3,37,1,3,130,250,0,0,0,3.5,3,0.0,3.0,0
4,41,0,2,130,204,0,2,0,1.4,1,0.0,3.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45,1,1,110,264,0,0,0,1.2,2,0.0,7.0,1
299,68,1,4,144,193,1,0,0,3.4,2,2.0,7.0,2
300,57,1,4,130,131,0,0,1,1.2,2,1.0,7.0,3
301,57,0,2,130,236,0,2,0,0.0,2,1.0,3.0,1
302,38,1,3,138,175,0,0,0,0.0,1,NaN,3.0,0

In [13]:
df_new['ca'] = df_new['ca'].fillna(df['ca'].mode()[0]) #[0] is given for mode to fill values to rows
df_new

,Age,Sex,cp,trestbps,chol,fbs,restecg,exang,oldpeak,slope,ca,thal,Presence
0,63,1,1,145,233,1,2,0,2.3,3,0.0,6.0,0
1,67,1,4,160,286,0,2,1,1.5,2,3.0,3.0,2
2,67,1,4,120,229,0,2,1,2.6,2,2.0,7.0,1
3,37,1,3,130,250,0,0,0,3.5,3,0.0,3.0,0
4,41,0,2,130,204,0,2,0,1.4,1,0.0,3.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45,1,1,110,264,0,0,0,1.2,2,0.0,7.0,1
299,68,1,4,144,193,1,0,0,3.4,2,2.0,7.0,2
300,57,1,4,130,131,0,0,1,1.2,2,1.0,7.0,3
301,57,0,2,130,236,0,2,0,0.0,2,1.0,3.0,1
302,38,1,3,138,175,0,0,0,0.0,1,0.0,3.0,0

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [15]:
#Defining input and output variables
y = df_new["Presence"]
x = df_new.drop(["Presence"], axis=1)

In [16]:
#Splitting data as train and test
x_train,x_test,y_train, y_test = train_test_split( x,y , test_size=0.2, random_state = 10)
model = LogisticRegression(max_iter=100000)

In [17]:
x_train.isna().sum()

Age         0
Sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
exang       0
oldpeak     0
slope       0
ca          0
thal        1
dtype: int64

In [18]:
x_train = x_train.fillna(x_train.mean())
x_test  = x_test.fillna(x_test.mean())

In [19]:
#Training my model
model.fit(x_train, y_train)

LogisticRegression(max_iter=100000)

In [20]:
y_pred = model.predict(x_test)
y_pred

array([0, 2, 1, 2, 0, 1, 0, 0, 0, 2, 0, 3, 4, 0, 0, 3, 1, 0, 3, 0, 0, 0,
       0, 1, 0, 0, 3, 0, 2, 3, 1, 0, 0, 3, 2, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 2, 3, 0, 0, 2, 4, 0, 0], dtype=int64)

In [21]:
#Evalutating predictions
accuracy = accuracy_score(y_test,y_pred)
print("Accuracy of the model: ", accuracy)

Accuracy of the model:  0.5573770491803278

In [22]:
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[28  1  1  1  0]
 [ 3  3  1  1  0]
 [ 2  4  1  1  1]
 [ 0  2  3  2  1]
 [ 0  2  1  2  0]]

In [23]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.85      0.90      0.88        31
           1       0.25      0.38      0.30         8
           2       0.14      0.11      0.12         9
           3       0.29      0.25      0.27         8
           4       0.00      0.00      0.00         5

    accuracy                           0.56        61
   macro avg       0.31      0.33      0.31        61
weighted avg       0.52      0.56      0.54        61